### PR TITLE
Dependency Upgrade & New Theme Integration

### PR DESCRIPTION
**Pull request by maierj**

### CODE REVIEW

**Comment by pancetta** [comment]
Hi @maierj, what is the status here?

**Comment by maierj** [comment]
> Hi @maierj, what is the status here?

@pancetta Last issue is merge conflicts, I'll resolve them this week and let you know when the PR is "mergeable" from our side.

**Comment by pancetta** [comment]
This is now three weeks ago. Any progress?

**Comment by lisawim** [comment]
I really like the theme of the PinT website! However, I cannot click on the menu button on the upper right, I don't know if I'm the only one with this issue. If this works for anyone else, ignore this comment!

**Comment by pancetta** [comment]
Works for me on macOS with Firefox and Safari. I guess you mean with Android or iOS? This I can confirm indeed.

**Comment by lisawim** [comment]
I tried it on iOS with Safari and on Ubuntu with Firefox where it does not work.

**Pull request merged**
