### PR TITLE
Add/pint flow

### PR DESCRIPTION
**Pull request by danielru**

### CODE REVIEW

**Comment by pancetta** [comment]
You want to see this sdc.bib online?

**Comment by danielru** [comment]
When I test this locally, the entries from `sdc.bib` do not appear in the [list of PINT references](http://www.parallelintime.org/references/index.html) which is at is should be - can you confirm this?

**Comment by pancetta** [comment]
Even if they don't, why upload this file here?

**Comment by danielru** [comment]
Because I need the Boris SDC reference in a project website. Is there any harm in having the file online?

**Comment by pancetta** [comment]
No, all good. We just may consider moving it away from the `_bibliography` top directory to something like `_bibliography/other` or `_bibliography/projects` or so.

**Comment by danielru** [comment]
Hm, I am not quite sure if/how this works - the `_config.yml` file tells jekyll-scholar to look in `_bibliography` for bib files. I have not tried if this means that it also looks in subdirectories.

**Comment by pancetta** [comment]
Check [this](https://github.com/JLESC/jlesc.github.io/tree/source/_bibliography) out and [this](https://github.com/JLESC/jlesc.github.io/blob/source/_config.yml#L106) and [this](https://github.com/JLESC/jlesc.github.io/blob/source/_projects/Lossy_checkpoint_restart.md). It'll work!

**Comment by danielru** [comment]
...turns out it is really simple.

**Comment by pancetta** [comment]
Uh, that was quick!

**Pull request merged**
