### PR TITLE
adding awesome publication list with statistics graph

### PR DESCRIPTION
**Pull request by torbjoernk**
Todo: use cross-references on other pages than the PFASST method page

### CODE REVIEW

**Comment by danielru** [comment]
I installed jekyll-scholar, but now when serving the page with jekyll, I get an error message: *Liquid Exception: invalid byte sequence in US-ASCII in _methods/pfasst.markdown* 

Is there another gem I need to install?

**Comment by danielru** [comment]
Nope, setting the environment variable *export LC_ALL=en_US.UTF-8* solved the issue.

**Comment by danielru** [comment]
Is there an easy way to add a feature to export the figure as PNG or so?

**Comment by torbjoernk** [comment]
To download the chart, right click it and "save image as ...". Link to BibTeX added. Will be working once this is merged into the `source` branch.

**Comment by danielru** [comment]
The right click does not work for me, but this is probably a Mac thing? (I use control + click and it just offers *save page as*, no *save image as*)

**Pull request merged**
